apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - name: api
      port: {{ .Values.backend.ports.api }}
      targetPort: {{ .Values.backend.ports.api }}
    - name: frontend
      port: {{ .Values.backend.ports.frontend }}
      targetPort: {{ .Values.backend.ports.frontend }}
  type: ClusterIP
